<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>BeeDay.Web</AssemblyName>
    <RootNamespace>BeeDay.Web</RootNamespace>
    <UserSecretsId>BeeDay-Web-Identity</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="../BeeDay.Application/BeeDay.Application.csproj" />
    <ProjectReference Include="../BeeDay.Domain/BeeDay.Domain.csproj" />
    <ProjectReference Include="../BeeDay.Infrastructure/BeeDay.Infrastructure.csproj" />
  </ItemGroup>
</Project>
