// <auto-generated />
using System;
using System.Collections.Generic;
using BeeDay.Infrastructure.Persistence.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeeDay.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(BeeDayDbContext))]
    [Migration("20260803111144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeeDay.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Attribute")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Featured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WalletTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WalletTagId")
                        .HasDatabaseName("IX_Transactions_Tag");

                    b.HasIndex("WalletId", "TransactionDate")
                        .HasDatabaseName("IX_Transactions_Wallet_Date");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Transactions_Type", "[Type] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset?>("EmailConfirmedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("HasCompletedOnboarding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SessionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<byte>("Theme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.HasIndex("Nickname")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Nickname")
                        .HasFilter("[Nickname] <> N''");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Language", "[Language] IN (0, 1)");

                            t.HasCheckConstraint("CK_Users_Theme", "[Theme] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_UserTokens_Hash");

                    b.HasIndex("UserId", "Type", "ExpiresAtUtc")
                        .HasDatabaseName("IX_UserTokens_User");

                    b.ToTable("UserTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserTokens_Type", "[Type] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Wallets_User");

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.WalletTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasDefaultValue("#7A4FCB")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_WalletTags_User_Name");

                    b.ToTable("WalletTags", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletTags_Color", "[Color] LIKE '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]'");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Experience.ExperienceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("ExperienceAfter")
                        .HasColumnType("bigint");

                    b.Property<long>("ExperienceBefore")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("int");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("int");

                    b.Property<byte>("RewardType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Source", "BeeDay.Domain.Experience.ExperienceEntry.Source#ExperienceSource", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("SourceDescription");

                            b1.Property<Guid?>("ReferenceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SourceId");

                            b1.Property<byte>("Type")
                                .HasColumnType("tinyint")
                                .HasColumnName("SourceType");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GrantedAtUtc")
                        .HasDatabaseName("IX_ExperienceEntries_User_Time");

                    b.ToTable("ExperienceEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExperienceEntries_RewardType", "[RewardType] = 0");

                            t.HasCheckConstraint("CK_ExperienceEntries_SourceType", "[SourceType] BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Habit", b =>
                {
                    b.HasBaseType("BeeDay.Domain.Entities.Activity");

                    b.Property<byte>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<byte>("Direction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.Property<int>("NegativeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("PositiveCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte>("ResetCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasIndex("UserId", "Position")
                        .HasDatabaseName("IX_Habits_User_Position");

                    b.ToTable("Habits", null, t =>
                        {
                            t.HasCheckConstraint("CK_Habits_Attribute", "[Attribute] IN (1, 2, 3, 4) OR [Attribute] IS NULL");

                            t.HasCheckConstraint("CK_Habits_Difficulty", "[Difficulty] IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_Habits_Direction", "[Direction] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Habits_ResetCounter", "[ResetCounter] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Project", b =>
                {
                    b.HasBaseType("BeeDay.Domain.Entities.Activity");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasDefaultValue("#7A4FCB")
                        .IsFixedLength();

                    b.Property<DateOnly?>("ExpectedDate")
                        .HasColumnType("date");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasIndex("UserId", "Position")
                        .HasDatabaseName("IX_Projects_User_Position");

                    b.ToTable("Projects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Projects_Attribute", "[Attribute] IN (1, 2, 3, 4) OR [Attribute] IS NULL");

                            t.HasCheckConstraint("CK_Projects_Color", "[Color] LIKE '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]'");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.RecurringTask", b =>
                {
                    b.HasBaseType("BeeDay.Domain.Entities.Activity");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<byte>("Repeat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasIndex("UserId", "Position")
                        .HasDatabaseName("IX_RecurringTasks_User_Position");

                    b.ToTable("RecurringTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringTasks_Attribute", "[Attribute] IN (1, 2, 3, 4) OR [Attribute] IS NULL");

                            t.HasCheckConstraint("CK_RecurringTasks_Repeat", "[Repeat] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Todo", b =>
                {
                    b.HasBaseType("BeeDay.Domain.Entities.Activity");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasIndex("ProjectId", "Position")
                        .HasDatabaseName("IX_Todos_Project_Position");

                    b.HasIndex("UserId", "Id")
                        .HasDatabaseName("IX_Todos_User");

                    b.ToTable("Todos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Todos_Attribute", "[Attribute] IN (1, 2, 3, 4) OR [Attribute] IS NULL");
                        });
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Wallets_WalletId");

                    b.HasOne("BeeDay.Domain.Entities.WalletTag", null)
                        .WithMany()
                        .HasForeignKey("WalletTagId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Transactions_WalletTags_WalletTagId");
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.User", b =>
                {
                    b.OwnsOne("BeeDay.Domain.Experience.UserExperience", "Experience", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("RowVersion")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("rowversion");

                            b1.Property<long>("TotalExperience")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L);

                            b1.HasKey("UserId");

                            b1.ToTable("UserExperience", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Experience")
                        .IsRequired();
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserTokens_Users_UserId");
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Wallets_Users_UserId");
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.WalletTag", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WalletTags_Users_UserId");
                });

            modelBuilder.Entity("BeeDay.Domain.Experience.ExperienceEntry", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExperienceEntries_Users_UserId");
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Habit", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Habits_Users_UserId");
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Project", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Projects_Users_UserId");
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.RecurringTask", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecurringTasks_Users_UserId");
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Todo", b =>
                {
                    b.HasOne("BeeDay.Domain.Entities.Project", null)
                        .WithMany("Todos")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Todos_Projects_ProjectId");

                    b.HasOne("BeeDay.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Todos_Users_UserId");
                });

            modelBuilder.Entity("BeeDay.Domain.Entities.Project", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
