<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../LevelUp.Application/LevelUp.Application.csproj" />
    <ProjectReference Include="../LevelUp.Domain/LevelUp.Domain.csproj" />
    <ProjectReference Include="../LevelUp.Infrastructure/LevelUp.Infrastructure.csproj" />
  </ItemGroup>
</Project>
